//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod local_src;
pub mod local_src_folder;
pub mod netease_src;
pub mod play_queue;
pub mod play_queue_track;
pub mod playlist;
pub mod playlist_track;
pub mod track;
pub mod user;
pub mod user_playlist;
