//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "local_src_folder")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub path: String,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::local_src::Entity")]
  LocalSrc,
}

impl Related<super::local_src::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::LocalSrc.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
