//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "netease_src")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub track_id: i32,
  pub netease_id: String,
  #[sea_orm(column_type = "Double", nullable)]
  pub pop: Option<f64>,
  pub raw_json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::track::Entity",
    from = "Column::TrackId",
    to = "super::track::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Track,
}

impl Related<super::track::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Track.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
