//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "playback")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub playlist_id: i32,
  pub position: i32,
  pub playing: bool,
  pub started_at: DateTimeUtc,
  pub paused_at: u32,
  pub created_at: DateTimeUtc,
  pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::playlist::Entity",
    from = "Column::PlaylistId",
    to = "super::playlist::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Playlist,
  #[sea_orm(has_many = "super::user::Entity")]
  User,
}

impl Related<super::playlist::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Playlist.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
