//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_playlist")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub user_id: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub playlist_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::playlist::Entity",
    from = "Column::PlaylistId",
    to = "super::playlist::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Playlist,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::playlist::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Playlist.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
